[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "opencv-python>=4.11.0.86",
    "python-multipart>=0.0.20",
    "ultralytics>=8.3.147",
    "uvicorn>=0.34.3",
]
